[package]
name = "tarkov"
version = "0.1.0"
authors = ["Dan Kyung <dan@kyung.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "2.0.0", features = ["openssl"] }
